-- MySQL Script generated by MySQL Workbench
-- Thu Jan 22 15:05:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dispositivo` (
  `id` VARCHAR(50) NOT NULL,
  `parametro` MEDIUMTEXT NULL,
  `tipo` MEDIUMTEXT NULL,
  `stato` MEDIUMTEXT NULL,
  `attivo` TINYINT NULL,
  `created_at` DATETIME NULL,
  `model` MEDIUMTEXT NULL,
  `stanza` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivo_stanza_idx` (`stanza` ASC),
  CONSTRAINT `fk_dispositivo_stanza`
    FOREIGN KEY (`stanza`)
    REFERENCES `mydb`.`Stanza` (`id`))
ENGINE = InnoDB; 

-- -----------------------------------------------------
-- Table `mydb`.`Stanza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stanza` (
  `id` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `mq` DOUBLE NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Communication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Communication` (
  `id` INT NOT NULL,
  `esito` TINYTEXT NULL,
  `tipo` TINYTEXT NULL,
  `value` MEDIUMTEXT NULL,
  `dispositivo` VARCHAR(50) NULL,
  `last_update` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `dispositivo_idx` (`dispositivo` ASC) VISIBLE,
  CONSTRAINT `fk_communication_dispositivo`
    FOREIGN KEY (`dispositivo`)
    REFERENCES `mydb`.`Dispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Misura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Misura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NULL,
  `unita` VARCHAR(50) NULL,
  `valore` DOUBLE NOT NULL,
  `stanza` VARCHAR(50) NULL,
  `timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`stanza` ASC) VISIBLE,
  CONSTRAINT `fk_misura_stanza`
    FOREIGN KEY (`stanza`)
    REFERENCES `mydb`.`Stanza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scenario` (
  `id` VARCHAR(50) NOT NULL,
  `nome` MEDIUMTEXT NULL,
  `tipo` MEDIUMTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `attivo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ScenarioStanzaConfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ScenarioStanzaConfig` (
  `id` VARCHAR(50) NOT NULL,
  `stanza` VARCHAR(50) NULL,
  `scenario` VARCHAR(50) NULL,
  `tipo_parametro` MEDIUMTEXT NULL,
  `tipo_valore` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`stanza` ASC) VISIBLE,
  INDEX `id_idx1` (`scenario` ASC) VISIBLE,
  CONSTRAINT `fk_config_stanza`
    FOREIGN KEY (`stanza`)
    REFERENCES `mydb`.`Stanza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idConfig`
    FOREIGN KEY (`scenario`)
    REFERENCES `mydb`.`Scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
